CREATE TABLE DIR_M_GAME(
	ID			TINYINT UNSIGNED	PRIMARY KEY						COMMENT 'ゲームID',
	TITLE		VARCHAR(255)		NOT NULL						COMMENT 'タイトル',
	VALIDATOR	VARCHAR(255)		CHARACTER SET ascii NOT NULL	COMMENT '検証URL',
	NOTE		TEXT												COMMENT '備考'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = '対象ゲームマスタ';

CREATE TABLE DIR_T_USER(
	ID				INTEGER UNSIGNED	PRIMARY KEY					COMMENT 'ユーザID',
	EMAIL			VARCHAR(255)		CHARACTER SET ascii UNIQUE	COMMENT 'メールアドレス',
	EMAIL_VALID		VARCHAR(255)		CHARACTER SET ascii 		COMMENT 'Eメール認証コード',
	NOTIFY_SERVICE	BOOLEAN				NOT NULL DEFAULT FALSE		COMMENT 'サービス内キャンペーンのメール通知有無',
	NOTIFY_ADS		BOOLEAN				NOT NULL DEFAULT FALSE		COMMENT 'その他danmaqの広告宣伝のメール通知有無',
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'ユーザアカウント一覧';
