INSERT INTO DIR_GAME_ACCOUNT (
	ID,				USER_ID,		GAME_ID,	PASSWD,		NICKNAME,
	INTRODUCTION,	REGIST_TIME,	RENEW_TIME,	LOGIN_TIME
)
VALUES(
	?,				?,				?,			?,			?,
	?,				NOW(),			NOW(),		NOW()
);
