SELECT		USER_ID,
			GAME_ID,
			PASSWD,
			NICKNAME,
			INTRODUCTION,
			UNIX_TIMESTAMP(REGIST_TIME)	AS REGIST_TIME,
			UNIX_TIMESTAMP(RENEW_TIME)	AS RENEW_TIME,
			UNIX_TIMESTAMP(LOGIN_TIME)	AS LOGIN_TIME,
			LOGIN_COUNT,
			NOTES
	FROM	DIR_GAME_ACCOUNT
	WHERE	ID = ?;
