SELECT		GACCOUNT_ID,
			PASSWD,
			SCORE0,
			SCORE1,
			SCORE2,
			SCORE3,
			SCORE4,
			SCORE5,
			SCORE6,
			SCORE7,
			INJUSTICE,
			WITHDRAW,
			UNIX_TIMESTAMP(REGIST_TIME)	AS REGIST_TIME,
			REMOTE_ADDR,
			REMOTE_HOST,
			USER_AGENT,
			NOTES
	FROM	DIR_SCORE
	WHERE	ID	= ?;
